/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ithm_lotteryhm28_NativeValue */

#ifndef _Included_com_ithm_lotteryhm28_NativeValue
#define _Included_com_ithm_lotteryhm28_NativeValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ithm_lotteryhm28_NativeValue
 * Method:    getAgenterPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ithm_lotteryhm28_NativeValue_getAgenterPassword
  (JNIEnv *, jclass);

/*
 * Class:     com_ithm_lotteryhm28_NativeValue
 * Method:    getDesPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ithm_lotteryhm28_NativeValue_getDesPassword
  (JNIEnv *, jclass);

/*
 * Class:     com_ithm_lotteryhm28_NativeValue
 * Method:    getLotteryUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ithm_lotteryhm28_NativeValue_getLotteryUrl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
